# Generated by Django 5.2.7 on 2025-10-28 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacialPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('front', 'Face (Frontal)'), ('left', 'Côté Gauche'), ('right', 'Côté Droit'), ('up', 'Vers le Haut'), ('down', 'Vers le Bas')], max_length=20)),
                ('photo', models.ImageField(upload_to='facial_photos/%Y/%m/%d/')),
                ('photo_base64', models.TextField(blank=True, help_text='Base64 encoded image for easy transmission')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Photo principale pour la reconnaissance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facial_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('user', 'position')},
            },
        ),
    ]
