# Generated by Django 5.2.7 on 2025-11-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_facialphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='facialphoto',
            name='face_embedding',
            field=models.TextField(blank=True, help_text='Face embedding stored as JSON string'),
        ),
    ]
