# Generated by Django 5.2.7 on 2025-11-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_facialphoto_face_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_subcategory', models.CharField(blank=True, max_length=255, null=True)),
                ('store_name', models.CharField(max_length=50)),
                ('product_link', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('availability', models.CharField(blank=True, max_length=50, null=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('prev_price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('images_links', models.JSONField(blank=True, default=list)),
                ('product_reference', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['store_name'], name='accounts_pr_store_n_26bf4e_idx'), models.Index(fields=['category'], name='accounts_pr_categor_82579f_idx')],
            },
        ),
    ]
