# Generated by Django 5.2.7 on 2025-11-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_product'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_store_n_a7345a_idx',
            old_name='accounts_pr_store_n_26bf4e_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_categor_fce6e6_idx',
            old_name='accounts_pr_categor_82579f_idx',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
