# Generated by Django 5.2.7 on 2025-11-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_driver_orderassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('processing', 'En cours de traitement'), ('shipped', 'Expédiée'), ('accepted', 'Acceptée par le livreur'), ('in_transit', 'En transit'), ('delivered', 'Livrée'), ('received', 'Reçue'), ('disputed', 'Litigeuse'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
