# Generated by Django 5.2.7 on 2025-11-19 12:02
# Field already added in 0010, making this migration a no-op

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_driveravailability_deliveryday_deliveryroute'),
    ]

    operations = [
        # Field scheduled_delivery_date already added in 0010
    ]
